### ISSUE TITLE
working on it

### ISSUE THREAD

**Issue by ZunayedDihan** [ZunayedDihan/android_device_infinix_X6827#1] opened 2023-05-11 15:59 UTC

**Comment by ZunayedDihan** [comment] 2023-05-11 16:12
@lopestom

**Comment by lopestom** [comment] 2023-05-11 18:33
> @lopestom

Great.

## How updating DT to A11 & A12:

#### For android.hardware.boot@1.0-impl-1.2-mtkimpl.so you can has this file from two ways:
 - Unpack boot.img and look `/ramdisk/system/lib64/hw`;
 - Unpack vendor.img from super.img and look `/vendor/lib64/hw`.

Now you put file in `/system/lib64/hw` folder of your repo like same example of this: https://github.com/lopestom/twrp_device_ulefone_Note_11P/tree/android-11.0/recovery/root/system/lib64/hw

#### For mtk_plpath_utils you can has this file from two ways:
 - Unpack boot.img and look `/ramdisk/system/bin`;
 - Unpack vendor.img from super.img and look `/system/bin`.

Now you put file in `/system/bin` folder of your repo like same example of this: https://github.com/lopestom/twrp_device_ulefone_Note_11P/tree/android-11.0/recovery/root/system/bin

### You need look and fix structure of `/recovery/root` like this: https://github.com/lopestom/twrp_device_infinix_x697/tree/A11/recovery/root

##### If you want compiling that files from your repo
Use this: https://github.com/lopestom/android_hardware_mediatek

**Comment by lopestom** [comment] 2023-05-11 18:34
WIP

You have device in your hands or other user have?

> Do you have discord or telegram so that ww can contact you more easily?

No.... IdL

>also for  mtk_plpath_utils will this be okey as i can't find in /vendor/system folder there

Read again my message....
```
infinix-user-12-SP1A.210812.016-289671-release-keys/system/system/bin/mtk_plpath_utils
```

If you want more help so don't forget about collaborator. I can't edit any file.

**Comment by ZunayedDihan** [comment] 2023-05-11 22:28
@lopestom https://github.com/ZunayedDihan/android_device_infinix_X6827/invitations

🙂

**Comment by ZunayedDihan** [comment] 2023-05-11 22:36
I have the device in my hand also but as of now its my primary device

**Comment by ZunayedDihan** [comment] 2023-05-11 22:37
Extracted firmware link : https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/tree/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/

**Comment by lopestom** [comment] 2023-05-12 00:15
> Extracted firmware link : https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/tree/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/

https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/bootimg/ramdisk/system/bin/mtk_plpath_utils

or
https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/system/system/bin/mtk_plpath_utils

**Comment by lopestom** [comment] 2023-05-12 00:31
recovery/root/vendor/etc/vintf/
https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/vendor/etc/vintf/compatibility_matrix.xml
........
.....
...
..
.
You need look and fix structure of /recovery/root like this: https://github.com/lopestom/twrp_device_infinix_x697/tree/A11/recovery/root

**Comment by ZunayedDihan** [comment] 2023-05-12 05:10
![Screenshot_20230512-110901.png](https://github.com/ZunayedDihan/android_device_infinix_X6827/assets/37245252/21a901a4-4389-41dd-ae14-401e23f065ec)

Can't find these two files in tree do i need to pick these two from your tree? Like which ever i don't find pick from your dt?

**Comment by ZunayedDihan** [comment] 2023-05-12 05:12
And should i keep as compatibility_matrix.xml or rename it to manifest.xml?

**Comment by ZunayedDihan** [comment] 2023-05-12 06:19
these are the files i didn't find in my dt
https://nekobin.com/yepisalacu

**Comment by ZunayedDihan** [comment] 2023-05-12 06:26
Also i guess i missed your bootctrl fix can you send me that again? Cause here when i started to lunch ut came with _PRODUCT_STATIC_BOOT_CONTROL_HAL is obsolete_

**Comment by ZunayedDihan** [comment] 2023-05-12 08:51
This is the full error message:
https://nekobin.com/warefikale

Also if i compile without bootctrl then getting boot img size exceeded :3

**Comment by lopestom** [comment] 2023-05-12 13:29
> This is the full error message: https://nekobin.com/warefikale
> 
> Also if i compile without bootctrl then getting boot img size exceeded :3

You canoot compile anything now! The DT is not complete!

**Comment by lopestom** [comment] 2023-05-12 13:40
> Also i guess i missed your bootctrl fix can you send me that again? Cause here when i started to lunch ut came with _PRODUCT_STATIC_BOOT_CONTROL_HAL is obsolete_

look again the message above. But you write for using stock files so copy & paste files.

> And should i keep as compatibility_matrix.xml or rename it to manifest.xml?

2 files in the \system\etc\vintf: https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/system/system/etc/vintf/manifest.xml
https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/system/system/etc/vintf/compatibility_matrix.device.xml

2 files in the \vendor\etc\vintf: https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/tree/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/vendor/etc/vintf

> ![Screenshot_20230512-110901.png](https://user-images.githubusercontent.com/37245252/237875468-21a901a4-4389-41dd-ae14-401e23f065ec.png)
> 
> Can't find these two files in tree do i need to pick these two from your tree? Like which ever i don't find pick from your dt?

init.....usb.rc is from file working correctly in all DT so i'ts from some files parts taken from system/vendor of the init.rc, init.usb.rc, init.usb.configfs.rc and init.mt6xxx.usb.rc
uevent.rc is from \vendor\etc as https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/vendor/etc/ueventd.rc and renamed.

**Comment by ZunayedDihan** [comment] 2023-05-12 13:57
and what about [android.hardware.keymaster@4.0-service.beanpod && [teei_daemon] ? where to get them?

**Comment by ZunayedDihan** [comment] 2023-05-12 14:02
also don't see these files <https://github.com/lopestom/twrp_device_infinix_x697/tree/A11/recovery/root/vendor/thh/ta>

**Comment by lopestom** [comment] 2023-05-12 14:07
> and what about [[android.hardware.keymaster@4.0-service.beanpod](mailto:android.hardware.keymaster@4.0-service.beanpod) && [teei_daemon] ? where to get them?
> also don't see these files https://github.com/lopestom/twrp_device_infinix_x697/tree/A11/recovery/root/vendor/thh/ta
> these are the files i didn't find in my dt https://nekobin.com/yepisalacu

The Realme - Tecno and Infinix have same (+/-) structure, script and files for trustonic cryptografy. So the android.hardware.keymaster@4.1-service.trustonic files appears in the https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/vendor/bin/hw/android.hardware.keymaster@4.1-service.trustonic

For trustonic is need more files than normal quantity have. I won't indicate all the files here because the possibility of not having encryption/decryption depends on each part and the files are listed in the other DT as a reference.
I think your boot.img has 40MB and maybe so ***MAYBE*** copying these files to DT and compiling TWRP.img get size more than 40MB.
This answers the question below.

For devices with 32MB (recovery.img or boot.img) so the process to crypt/decrypt is not possible because same answer of size img. But these devices not have trustonic. These twrp.img with crypt/decrypt files need 38MB minimum size. For trustonic you need put files and try compiling to knew. If you see `size exceeded` so try removing files that not need or remove crypt/decrypt files so TWRP not have crypt/decrypt mode.
I not explain all here but since A12 with keymint was released from G so the much files like keystore2 has more than 1~2MB and final img depending of the recovery/boot size partition.

> This is the full error message: https://nekobin.com/warefikale
> 
> .................... getting boot img size exceeded :3

Therefore if you have same message compiling img so your device cannot have crypt/decrypt mode.

**Comment by ZunayedDihan** [comment] 2023-05-12 14:15
the boot.img is 32mb so i guess from your above msg encrypt/decrypt isn't possible

**Comment by ZunayedDihan** [comment] 2023-05-12 14:17
last time i tried without bootctrl its already saying exceeding boot partition size

**Comment by ZunayedDihan** [comment] 2023-05-12 14:18
i have forced pushed as of now can you check that so far i did is good or i did any mistake?

**Comment by lopestom** [comment] 2023-05-12 15:35
> i have forced pushed as of now can you check that so far i did is good or i did any mistake?

I not know how you compile so with your PC or ??
So if you can fork [this ](https://github.com/azwhikaru/Action-TWRP-Builder) and make actions compile for we can know about compiling errors - solutions online.

**Comment by ZunayedDihan** [comment] 2023-05-12 15:39
I do on my laptop kinda its more easy for me if you want i can leave the log each time on nekobin and share error here

**Comment by ZunayedDihan** [comment] 2023-05-12 15:40
Lemme compile in this state then and let you know which kind of error is coming

**Comment by ZunayedDihan** [comment] 2023-05-12 15:41
Do you have telegram or any other platform so that it can be more easy communicating there :3

**Comment by ZunayedDihan** [comment] 2023-05-12 15:49
https://nekobin.com/xopezajelo

**Comment by ZunayedDihan** [comment] 2023-05-12 15:50
i have copied [android.hardware.boot@1.0-impl-1.2-mtkimpl.so] into dt so should i nuke bootctrl lines from device.mk?

**Comment by lopestom** [comment] 2023-05-12 17:03
> Do you have telegram or any other platform so that it can be more easy communicating there :3

no

> https://nekobin.com/xopezajelo

looking just now.
Your respost look in the line 5 - 13 - 18
About this: https://android.googlesource.com/platform/build/+/master/Changes.md#PRODUCT_STATIC_BOOT_CONTROL_HAL. Maybe very thing changed.
So use stock file!

> i have copied [[android.hardware.boot@1.0-impl-1.2-mtkimpl.so](mailto:android.hardware.boot@1.0-impl-1.2-mtkimpl.so)] into dt so should i nuke bootctrl lines from device.mk?

if compiling have errors about so....

----------------
Now I write to you because you send email and I wrote to you about learning or compile img file. So you answered that have learning.
Look I create A12_NoCrypt branch and you can see the compile img process: https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/4961155656/jobs/8877584144

Now read and ***READ***.
You're not the first and you won't be the last to come to me to find out how to do a DT and want a custom recovery img file.
But like others, you totally ignored what I wrote before!!
You didn't read the guide reference, you didn't read the reference MT6781 DT that I left. You did like others (9/10) who just want to copy and paste something. But you didn't copy/paste the MT6781 DT I left for you!
Asking is okay. But not reading the answers is leaving someone frustrated answering every part (maybe 1000) of what they need and what they don't.
If you really want to learn, you must have some sharp qualities: time, curiosity, reading and, above all, patience not to give up. Understanding what your device has, what the ROM offers and especially researching if it already exists are crucial parts of knowing.
I learned from a lot of reading. For the A12, there was nothing referenced, maybe because nobody wanted to share, maybe because many were really upgrading from A10 to A11 or from A11 to A12, because many still had recovery.img and maybe because many wait for others to do it.
I spent 3-6 months trying until I understood the errors, what was needed and found the correct settings. I still don't consider myself a developer! Even so, I still continue to read everything to A14. Everything can change at any moment and so it's just updating knowledge.
But without trying to learn, do something, read then you won't understand!

**Comment by lopestom** [comment] 2023-05-12 17:08
> https://nekobin.com/xopezajelo

Same error here: https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/4961155656/jobs/8877584144#step:16:13

Deleted `PRODUCT_STATIC_BOOT_CONTROL_HAL := \` from device.mk to new compile attempt.
https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/4961354108/jobs/8878034726

**Comment by ZunayedDihan** [comment] 2023-05-12 17:20
Okey got it. Kinda thing is i wasn't getting like somethings. Like you told me to take the reference dt and do recovery/root/ folder to be same structure. Some of the files were not found by me tthen you answered some question now i am not getting is should i take all the codes related to usb?  Also sorry i will kinda try to read more to learn 🙂

**Comment by lopestom** [comment] 2023-05-12 17:22
> Okey got it. Kinda thing is i wasn't getting like somethings. Like you told me to take the reference dt and do recovery/root/ folder to be same structure. Some of the files were not found by me tthen you answered some question now i am not getting is should i take all the codes related to usb? Also sorry i will kinda try to read more to learn slightly_smiling_face

I'm doing something simple for you to understand that your DT is not good. Even doing another branch, I know it can have many errors. So after that, I'll show you the way another way.

**Comment by ZunayedDihan** [comment] 2023-05-12 17:26
Okey i am following you..
I was confused about how to make the init usb rc file 🥲

**Comment by lopestom** [comment] 2023-05-12 17:33
> Okey i am following you.. I was confused about how to make the init usb rc file smiling_face_with_tear

It's not easy to do. We can copy any usb.rc from other same Soc-CPU and test. If you want need know so need trying get some PID-VID from device and Linux command. Look, I not use this a very time ago because the actual usb.rc working.
Answered you here: https://github.com/ZunayedDihan/android_device_infinix_X6827/issues/1#issuecomment-1545769314
```
init.....usb.rc is from file working correctly in all DT so i'ts from some files parts taken from system/vendor of the init.rc, init.usb.rc, init.usb.configfs.rc and init.mt6xxx.usb.rc
```


Other think is with DT from Nomercy / @Miichon and you attempt to have crypt/decrypt because not put correctly files since that is A11.

**Comment by ZunayedDihan** [comment] 2023-05-12 17:38
Ooo i thoughg you told me to see all related usb files in extracted firmware and make that 🙂
Sorry for not understanding

**Comment by lopestom** [comment] 2023-05-12 17:50
Okay. Compile process start
https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/4961354108/jobs/8878034726

But I can't promess img starting in the device so I not know if twrp (boot.img) can boot. Because that is need test.

When compile img file end so you can download img file here: https://github.com/lopestom/Action-Recovery-Builder-CT/releases
1h to do and look to X6827 name.

**Comment by ZunayedDihan** [comment] 2023-05-12 17:53
Okey cool thanks man i will test and let you know... What happened!

**Comment by lopestom** [comment] 2023-05-12 18:52
We have that with error:
`error: +out/target/product/X6827/boot.img too large (35543040 > 33484800)`

So need's removing more files in the DT.
But I'll put some `TW_EXCLUDE_` to try without deleting files.

Some changes & Add flags. New attempt to compile e know if img reducing.
https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/4962193623/jobs/8879949381

**Comment by ZunayedDihan** [comment] 2023-05-12 19:51
Ah okey got it.the commit messages help a lot

**Comment by lopestom** [comment] 2023-05-12 21:29
> Ah okey got it.the commit messages help a lot

Now you have more time to compare your DT https://github.com/ZunayedDihan/android_device_infinix_X6827/tree/vnd_x6827_h812-user-12-SP1A.210812.016-291059 with my changes to https://github.com/ZunayedDihan/android_device_infinix_X6827/tree/A12_NoCrypt

Look!!! Just now writing the attempt to compile img file get error:
`failed 2 minutes ago in 2h 12m 29s`
`error: +out/target/product/X6827/boot.img too large (34396160 > 33484800)`
Again you can see waht I wrote to you about size of twrp.img

I'm compiling new file with A12_NoCrypt branch forked from `infinix_x697/tree/A11/` 
 https://github.com/ZunayedDihan/android_device_infinix_X6827/issues/1#issuecomment-1544493649

But after 1:30h you can see if img file compiled or not. I need sleep now
https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/4963178090/jobs/8882128284

**Comment by ZunayedDihan** [comment] 2023-05-13 00:43
Cool it compiled i will test and let you know if.it booted or not

**Comment by ZunayedDihan** [comment] 2023-05-13 05:56
Sadly didn’t boot stuck in logo :')

**Comment by lopestom** [comment] 2023-05-13 15:54
> Sadly didn’t boot stuck in logo :')

Made this?
`fastboot flashing unlock_critical`

follow:
#### Install
Bootloader unlocked
`fastboot flashing unlock_critical`

Use stock vbmeta or [modified vbmeta](https://dl.google.com/developers/android/qt/images/gsi/vbmeta.img?hl=en-US) file [preferencial]

```
fastboot --disable-verification flash vbmeta vbmeta.img
fastboot flash boot boot.img
```

**Comment by ZunayedDihan** [comment] 2023-05-13 21:50
I used spflashtool🙂
Even if i get same result is there any way to get logs?

**Comment by lopestom** [comment] 2023-05-13 22:06
> I used spflashtoolslightly_smiling_face Even if i get same result is there any way to get logs?

Use fastboot mode - follow the instructions and let me know.

Very Realme - Tecno & Infinix are coming with protections. Some devices use MTKClient or MTKBypass to bypass protection.
I really not know if your device need.

In this installation phase, it is very important to write in detail what you do, to try to solve something.
I remembered that it is also important to have the same firmware version that is on your device.
Then confirm if the boot.img was used from your device or if the kernel was taken from https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/tree/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/
Device Information: `X6827-H812OPQ-S-OP-230403V890`

**Comment by ZunayedDihan** [comment] 2023-05-14 07:58
Its from the latest firmware so we all have the updated firmware

**Comment by MHFAYCEL** [comment] 2023-05-14 11:42
This is twrp for x6827 🙄 now v1200
I can help to build TWRP for it or still waiting

**Comment by MHFAYCEL** [comment] 2023-05-14 12:08
I tested stock on Logo 🙂

**Comment by lopestom** [comment] 2023-05-14 14:23
> Its from the latest firmware so we all have the updated firmware

> This is twrp for x6827 roll_eyes now v1200 I can help to build TWRP for it or still waiting

Upload stock boot from v1200.

**Comment by ZunayedDihan** [comment] 2023-05-14 17:49
Firmware v1200
Boot: https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/boot.img

@lopestom

**Comment by lopestom** [comment] 2023-05-14 19:14
> Firmware v1200 Boot: https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/boot.img
> 
> @lopestom

Same by here https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blame/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/bootimg/ramdisk/prop.default#L340

[MHFAYCEL](https://github.com/MHFAYCEL) say about V1200 so not V890

Some changes was made. Not know if this file is good: https://github.com/lopestom/Action-Recovery-Builder-CT/releases/download/4963178090/boot-TWRP-2.zip

@ZunayedDihan 
I undertand you using SPFT. But if you not follow my instructions and not confirm all of that so I cant help much.
You contact me about learning compile custom recovery. Now you have img file.
If not start, so you need solve that. Read and have more knowledge.
Just now I'll stop here because MHFAYCEL  say `I can help to build TWRP for it`.
You not alone now.

**Comment by MHFAYCEL** [comment] 2023-05-15 06:14
My friends, I modified the twrp of the infinix note 12 device, since it carries the same processor, I modified the space first, then modified the screen width, and modified prop.defult to support sdcard and OTG, and downloaded it to the device via fastboot. The original recovery disappeared, and he went to TWRP recovery without problems. There remains a problem that the interface does not appear, and even if you open the device, it opens without problems. This is what I have reached now. Who has an idea of ​​what the problem is or suggestions for a good day for you

**Comment by lopestom** [comment] 2023-05-15 13:06
> a problem that the interface does not appear, and even if you open the device, it opens without problems.

You made the PORT of file? TWRP version??
IN12 is not same 20s https://www.devicespecifications.com/en/comparison/5a34206bc5
TWRP-A11 is not same TWRP-12

**Comment by MHFAYCEL** [comment] 2023-05-15 14:45
https://forum.xda-developers.com/t/recovery-infinix-note-12-5g-twrp-3-7-0-x671-12-unofficial-teamwin-recovery-initial-release.4568137/

**Comment by lopestom** [comment] 2023-05-15 15:59
> https://forum.xda-developers.com/t/recovery-infinix-note-12-5g-twrp-3-7-0-x671-12-unofficial-teamwin-recovery-initial-release.4568137/

Infinix Note 12 5G ==>> mt6833

Infinix-X6827 ==>> Hot 20s -->> mt6781

IN12 -> mt6768

You're wrong method of PORT.

**Comment by ZunayedDihan** [comment] 2023-05-15 16:17
We need 6781 twrp to port not other ones

**Comment by ZunayedDihan** [comment] 2023-05-15 16:23
@lopestom senpai i had a question!
Like is there any way to get logs so that I can get where it is misbehaving and fix it?

**Comment by lopestom** [comment] 2023-05-15 16:34
> @lopestom senpai i had a question! Like is there any way to get logs so that I can get where it is misbehaving and fix it?

First you need install with my intructions. Use all that you can.
if no good so need try using MTKClient or/and MTKBypass - I really not know if your device has protections -- if you can install boot_patched.img with Magisk so I think not have protections --- but is need know!! is need confirm!!

You NEVER answered my questions about instructions https://github.com/ZunayedDihan/android_device_infinix_X6827/issues/1#issuecomment-1546758693

After that so you can change anything in DT for more tests with new img.

Much writing minus feedback = doubts

**Comment by ZunayedDihan** [comment] 2023-05-15 16:38
Oh i did all your steps sir,  also commands still in doesn't boot so to confirm i asked another person he hasn't replied me yet

**Comment by lopestom** [comment] 2023-05-15 17:43
> Oh i did all your steps sir, also commands still in doesn't boot so to confirm i asked another person he hasn't replied me yet

[/boot-TWRP-2.zip](https://github.com/lopestom/Action-Recovery-Builder-CT/releases/download/4963178090/boot-TWRP-2.zip) ??

**Comment by ZunayedDihan** [comment] 2023-05-15 18:01
Oh no not the lastest one yet i got a assignment due this week for which i need my phone i will get back to you on it as soon as possible

**Comment by MHFAYCEL** [comment] 2023-05-15 18:06
> Oh no not the lastest one yet i got a assignment due this week for which i need my phone i will get back to you on it as soon as possible

Use mtkauthbypass Toul v20 and V30 just work lower v850 
and if not crashed boot flash
 preloader.img
preloader_emmc
In fastboot

**Comment by lopestom** [comment] 2023-05-15 18:10
So I made some minimals changes to more tests. Bu I have other ideia about https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/bootimg/01_dtbdump_MT6781.dtb
This is only for remenber if others tests not helped.

Th img compiling now: https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/4984558247/jobs/8923047066

**Comment by MHFAYCEL** [comment] 2023-05-15 18:53
> > https://forum.xda-developers.com/t/recovery-infinix-note-12-5g-twrp-3-7-0-x671-12-unofficial-teamwin-recovery-initial-release.4568137/
> 
> Infinix Note 12 5G ==>> mt6833
> 
> Infinix-X6827 ==>> Hot 20s -->> mt6781
> 
> IN12 -> mt6768
> 
> You're wrong method of PORT.

Thank you. I cannot modify the sync repo method. I do not have much experience with the site. Is there another device with the same card for which a twrp has already been created?.

**Comment by lopestom** [comment] 2023-05-15 19:52
> > > https://forum.xda-developers.com/t/recovery-infinix-note-12-5g-twrp-3-7-0-x671-12-unofficial-teamwin-recovery-initial-release.4568137/
> > 
> > 
> > Infinix Note 12 5G ==>> mt6833
> > Infinix-X6827 ==>> Hot 20s -->> mt6781
> > IN12 -> mt6768
> > You're wrong method of PORT.
> 
> Thank you. I cannot modify the sync repo method. I do not have much experience with the site. Is there another device with the same card for which a twrp has already been created?.

If you want PORT same ***SOC*** (not card!!) so I have some img file. But you need know if your device has A10-A11-A12 and more important if has boot.img & recovery.mg or ONLY boot.img.

If you want a compiled img so it's a exclusive Custom Recovery with informations from your device so you can search for [device mt6768](https://github.com/search?q=device%20mt6768&type=repositories) and `fork` that to your personal github.

You will always get what you give. Being lazy is not interesting here. Not updating your mind and processes in the face of G updates will not make you a connoisseur!

I have experience with 10 years with Custom Recovery PORT. So that's is not new to me!
I was reading, slowly learning and as I gained some experience with Linux, with the improvement of the TeamWin-TWRP code, then compiling img files became easy.
But the most important thing I already wrote! Seek to read, understand, have knowledge, be curious to know what each part means or what it is used for and thus apply it to the device itself.
So also know how to troubleshoot compilation issues and also if TWRP needs fixing.

**Comment by lopestom** [comment] 2023-05-15 20:36
I'm closing this issue and opening other issue tab to more easy write/read.
Since the question of **how to make a DT has been resolved**, then there is nothing more to write here.

**Closed as completed by lopestom** 2023-05-15 20:36 UTC
